const imgAlbumArt = "/cover.png";

const HIGHLIGHTS = [
  {
    id: 1,
    show: 'Product Builder',
    episode: 'קרולינה פיין | בעיה תוך כדי נהיגה',
    timestamp: '14:22',
    date: 'Today',
    transcript:
      `"The data shows that people who maintain a sense of optimism — and choosing to act anyway."`,
    duration: '0:28',
  },
  {
    id: 2,
    show: 'Product Builder',
    episode: 'קרולינה פיין | בעיה תוך כדי נהיגה',
    timestamp: '08:47',
    date: 'Today',
    transcript:
      `"The data shows a consistent 40-year trend of declining extreme poverty worldwide. Most people don\u2019t know this."`,
    duration: '0:19',
  },
  {
    id: 3,
    show: 'Hard Fork',
    episode: 'AI in the Courtroom',
    timestamp: '31:05',
    date: 'Yesterday',
    transcript:
      `"There\u2019s no framework for this yet. Judges are being asked to rule on evidence generated by systems they fundamentally don\u2019t understand."`,
    duration: '0:22',
  },
  {
    id: 4,
    show: 'Radiolab',
    episode: 'The Longevity Paradox',
    timestamp: '19:33',
    date: 'Mar 24',
    transcript:
      `"Living to 120 sounds appealing until you ask: at what quality of life? That\u2019s the question nobody wants to answer."`,
    duration: '0:15',
  },
]

function IconBack() {
  return (
    <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
      <path d="M19 12H5M5 12L12 19M5 12L12 5" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  )
}
function IconShare() {
  return (
    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#b3b3b3" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/>
      <line x1="8.59" y1="13.51" x2="15.42" y2="17.49"/><line x1="15.41" y1="6.51" x2="8.59" y2="10.49"/>
    </svg>
  )
}
function IconDelete() {
  return (
    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#b3b3b3" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <polyline points="3 6 5 6 21 6"/><path d="M19 6l-1 14a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2L5 6"/>
      <path d="M10 11v6"/><path d="M14 11v6"/><path d="M9 6V4h6v2"/>
    </svg>
  )
}
function IconBookmark() {
  return (
    <svg width="14" height="14" viewBox="0 0 28 28" fill="#1DB954">
      <path d="M7 4h14a1 1 0 0 1 1 1v18l-8-4-8 4V5a1 1 0 0 1 1-1z"/>
    </svg>
  )
}

function HighlightCard({ item }) {
  return (
    <div className="bg-[#181818] rounded-2xl p-4 mb-3">
      {/* Header row */}
      <div className="flex items-center gap-3 mb-3">
        <img
          src={imgAlbumArt}
          alt="cover"
          className="w-[48px] h-[48px] rounded-lg object-cover flex-shrink-0"
        />
        <div className="flex-1 min-w-0">
          <p className="text-white text-[14px] font-semibold truncate leading-tight">{item.episode}</p>
          <p className="text-[#b3b3b3] text-[12px] mt-0.5">{item.show}</p>
        </div>
        <div className="flex flex-col items-end flex-shrink-0 gap-1">
          <div className="flex items-center gap-1">
            <IconBookmark />
            <span className="text-[#1DB954] text-[11px] font-semibold">{item.timestamp}</span>
          </div>
          <span className="text-[#535353] text-[11px]">{item.date}</span>
        </div>
      </div>

      {/* Transcript */}
      <div className="bg-[#121212] rounded-xl px-4 py-3 mb-3 border-l-2 border-[#1DB954]">
        <p className="text-[#e0e0e0] text-[14px] leading-[22px] italic">
          {item.transcript}
        </p>
        <p className="text-[#535353] text-[11px] mt-2">{item.duration} clip</p>
      </div>

      {/* Actions */}
      <div className="flex items-center justify-between">
        {/* Play clip */}
        <button className="flex items-center gap-2 bg-[#1DB954]/10 rounded-full px-4 py-2">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="#1DB954">
            <polygon points="5 3 19 12 5 21 5 3"/>
          </svg>
          <span className="text-[#1DB954] text-[13px] font-semibold">Play clip</span>
        </button>

        <div className="flex items-center gap-1">
          {/* Share */}
          <button className="w-[44px] h-[44px] flex items-center justify-center rounded-full">
            <IconShare />
          </button>
          {/* Delete */}
          <button className="w-[44px] h-[44px] flex items-center justify-center rounded-full">
            <IconDelete />
          </button>
        </div>
      </div>
    </div>
  )
}

// Group highlights by date
function groupByDate(items) {
  const groups = {}
  items.forEach(item => {
    if (!groups[item.date]) groups[item.date] = []
    groups[item.date].push(item)
  })
  return groups
}

export default function MyHighlights({ onBack }) {
  const groups = groupByDate(HIGHLIGHTS)

  return (
    <div className="bg-[#121212] w-full h-full flex flex-col overflow-hidden">
      {/* Header */}
      <div className="flex-shrink-0 pt-[54px] px-5 pb-4">
        <div className="flex items-center gap-3 mb-6">
          <button
            onPointerDown={onBack}
            className="w-[44px] h-[44px] flex items-center justify-center -ml-2"
          >
            <IconBack />
          </button>
          <div>
            <h1 className="text-white text-[24px] font-bold tracking-[-0.5px]">My Highlights</h1>
            <p className="text-[#b3b3b3] text-[13px] mt-0.5">{HIGHLIGHTS.length} saved moments</p>
          </div>
        </div>

        {/* Filter pills */}
        <div className="flex gap-2 overflow-x-auto pb-1 scrollbar-hide">
          {['All', 'Product Builder', 'Hard Fork', 'Radiolab'].map((label, i) => (
            <button
              key={label}
              className={`flex-shrink-0 rounded-full px-4 py-2 text-[13px] font-semibold border transition-colors ${
                i === 0
                  ? 'bg-white text-black border-white'
                  : 'bg-transparent text-[#b3b3b3] border-[#535353]'
              }`}
            >
              {label}
            </button>
          ))}
        </div>
      </div>

      {/* Scrollable list */}
      <div className="flex-1 overflow-y-auto px-5 pb-8">
        {Object.entries(groups).map(([date, items]) => (
          <div key={date} className="mb-2">
            <p className="text-[#b3b3b3] text-[12px] font-semibold uppercase tracking-widest mb-3">
              {date}
            </p>
            {items.map(item => (
              <HighlightCard key={item.id} item={item} />
            ))}
          </div>
        ))}
      </div>
    </div>
  )
}
